import { readFile, writeFile } from 'node:fs/promises';
import { escapeHtml, rankedEntries, renderCard, renderScores, repository, validateReview } from './scorecards.mjs';

const review = validateReview(JSON.parse(await readFile(new URL('./scores.json', import.meta.url), 'utf8')));
const entries = rankedEntries(review);
const previousLanding = await readFile(new URL('../index.html', import.meta.url), 'utf8').catch(error => {
  if (error.code === 'ENOENT') return '';
  throw error;
});
// Keep unreviewed implementations that a publishing workflow has added.
const unreviewedCards = [...previousLanding.matchAll(/<section\b[^>]*class="card"[^>]*>[\s\S]*?<\/section>/g)]
  .map(match => match[0])
  .filter(card => !entries.some(entry => card.includes(`href="${entry.folder}/"`)));
const reviewedDate = new Intl.DateTimeFormat('en-GB', {
  day: 'numeric', month: 'short', year: 'numeric', timeZone: 'UTC',
}).format(new Date(`${review.reviewedAt}T00:00:00Z`));

function document(title, stylesheet, content, script = '') {
  return `<!doctype html>
<!-- Generated by reviews/build.mjs from reviews/scores.json. -->
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<link rel="stylesheet" href="${stylesheet}" />
${script}
</head>
<body>
<main>
${content}
</main>
</body>
</html>
`;
}

const footer = `<footer>
  <a href="${repository}">github.com/rlorca/mall-action</a> ·
  <a href="${repository}/blob/main/one-shot-prompt.md">The prompt</a><br />
  A FLICKERSOFT fan homage, not affiliated with Taito or any parodied brand.
</footer>`;

const landing = document('MALL ACTION — implementation scores', 'reviews/style.css', `
  <h1>MALL ACTION</h1>
  <p class="sub">A SHOPPING MALL ESPIONAGE</p>
  <p class="intro">An 8-bit spy caper in an 80s shopping mall. The same one-shot prompt, built from scratch by different AI models.</p>
  <div class="review-summary">
    <p class="eyebrow">${entries.length} reviewed implementations · ${reviewedDate}</p>
    <p>Best score first. All scores are out of 10; overall is the equal average of the five categories.</p>
    <a href="reviews/index.html">Methodology &amp; full assessments <span aria-hidden="true">↗</span></a>
  </div>
  ${entries.map((entry, index) => renderCard(entry, review, index + 1)).join('\n\n  ')}${unreviewedCards.length ? `\n\n  ${unreviewedCards.join('\n\n  ')}` : ''}
  ${footer}
`, '<script type="module" src="reviews/enhance.mjs"></script>');

const assessments = entries.map((entry, index) => `<article class="assessment" id="${entry.branch}" aria-labelledby="${entry.branch}-title">
  <h2 id="${entry.branch}-title"><span class="rank">${String(index + 1).padStart(2, '0')}</span>${escapeHtml(entry.name)}</h2>
  <p class="review-note">${escapeHtml(entry.note)}</p>
  ${renderScores(entry, review.criteria)}
  <p class="snapshot">Snapshot <a href="${repository}/tree/${entry.commit}"><code>${entry.commit.slice(0, 12)}</code></a> · branch <code>${entry.branch}</code></p>
  <dl class="reasoning">${review.criteria.map(criterion => `<div><dt>${escapeHtml(criterion.label)}</dt><dd>${escapeHtml(entry.assessment[criterion.key])}</dd></div>`).join('\n')}</dl>
  <div class="verification"><h3>Verification</h3><ul>
    <li>${entry.verification.tests} tests passed.</li>
    <li>Build: ${escapeHtml(entry.verification.build)}.</li>
    <li>Runtime: ${escapeHtml(entry.verification.browser)}.</li>
  </ul></div>
  <p class="evidence">Source evidence: ${entry.evidence.map(source => `<a href="${repository}/blob/${entry.commit}/${source.path}${source.line ? `#L${source.line}` : ''}">${escapeHtml(source.label)}</a>`).join(' · ')}</p>
  <p class="back"><a href="../index.html">Back to implementations</a></p>
</article>`).join('\n\n');

const report = document('MALL ACTION — review methodology and assessments', 'style.css', `
  <p class="back"><a href="../index.html">← All implementations</a></p>
  <h1 class="report-title">IMPLEMENTATION REVIEW</h1>
  <p class="sub">${reviewedDate} · ${entries.length} current branch snapshots</p>
  <section class="methodology" aria-labelledby="methodology-title">
    <h2 id="methodology-title">How the scores work</h2>
    <p>These are editorial judgments about the implementations at the linked commits, including later fixes. They are not measurements of model capability or ratings of the original one-shot commits.</p>
    <p>Each category is scored from 0 to 10. Overall is their arithmetic mean, rounded to one decimal. Cards sort by that displayed overall score, then prompt completeness, then game design. Scores around 9 indicate strong implementation with minor gaps; 7–8 indicates a solid result with material weaknesses; 4–6 indicates a partial game; 0–3 indicates fundamental blockers or unfinished systems.</p>
    <dl class="reasoning">${review.criteria.map(criterion => `<div><dt>${escapeHtml(criterion.label)}</dt><dd>${escapeHtml(criterion.description)}</dd></div>`).join('\n')}</dl>
    <h3>Review scope</h3>
    <p>The review compared source, assets, tests, build configuration, and gameplay rules with the <a href="${repository}/blob/main/one-shot-prompt.md">original prompt</a>. Every implementation's test suite and production build was run. Haiku also received a separate TypeScript check because its build does not typecheck.</p>
    <p>Browser checks sampled launch, title, arrival, and mall presentation. Stronger implementations also received store-entry checks using prepared player positions; Fable and GPT-6.1 received package-search checks. Targeted probes reproduced the Haiku timing blocker and Gemini store-exit blocker. GPT-6 Sol's dead-spy and Black Friday defects were reproduced in Node.</p>
    <p>This was not an uninterrupted six-package walkthrough of all nine games. Unverified full-route completion is not claimed. Test counts are reported as context; they do not determine scores. Other findings come from source inspection and are described as inferences where relevant. Scores describe these source snapshots; published Play builds may change independently.</p>
  </section>
  <nav class="review-nav" aria-label="Implementation assessments">${entries.map(entry => `<a href="#${entry.branch}">${escapeHtml(entry.name)}</a>`).join('\n')}</nav>
  ${assessments}
  ${footer}
`);

await writeFile(new URL('../index.html', import.meta.url), landing);
await writeFile(new URL('./index.html', import.meta.url), report);
console.log(`Generated ${entries.length} ranked cards and assessments.`);
