import { wrap } from "./math.js";
const posts = (rows) =>
  rows.map(([caption, comment]) => ({ lines: caption.split(" / "), comment }));
export const ARRIVAL = posts([
  ["FEELING CUTE, / MIGHT DELETE LATER", "MOM: SO PROUD OF U"],
  ["FIRST DAY ON THE JOB! / #BLESSED", "BOSS: DELETE THIS"],
  ["MALL RAT? NO. / MALL AGENT.", "MOM: WEAR A JACKET"],
  ["ZIPLINE WAS $0. / PARKING WAS $12.", "DAD: TOLD U SO"],
  ["OUTFIT OF THE DAY: / TRENCHCOAT, AGAIN", "FOREVER12: 20% OFF!"],
  ["NO SPIES WERE HARMED / IN THIS SELFIE. YET.", "DIMITRI: :("],
  ["ROOFTOP VIBES / #UNDERCOVER", "HQ: WHY IS IT PUBLIC"],
  ["DON'T TELL HQ, I'M / HERE FOR PRETZELS", "HQ: WE CAN SEE THIS"],
  ["GOLDEN HOUR. / LICENSE TO CHILL.", "MOM: CALL YOUR MOTHER"],
  ["SECRET MISSION. / PLEASE LIKE & SHARE", "HQ: ...SERIOUSLY?"],
]);
export const COMPLETE = posts([
  ["MISSION COMPLETE. / ALSO BOUGHT SOCKS.", "MOM: WHAT COLOR?"],
  ["6 PACKAGES. / 0 RECEIPTS. #WIN", "RETURNS DESK: NO"],
  ["SAVED THE WORLD. / STILL NO PARKING.", "DAD: TYPICAL"],
  ["SPIES: 0 / ME: 1 #MALLRAT", "BORIS: REMATCH?"],
  ["GETAWAY CAR: / WOOD PANELING. ICONIC", "HQ: RETURN THE CAR"],
  ["TREATED MYSELF TO A / CINNABOMB. EARNED IT.", "MOM: EAT A VEGGIE"],
  ["HQ SAID KEEP IT QUIET / SO HERE IS A POST", "HQ: YOU'RE FIRED"],
  ["FOUND A PET ROCK. / HIS NAME IS KEVIN.", "KEVIN: ..."],
  ["BRB, RETURNING 6 / SUSPICIOUS PACKAGES", "MALL COP: WAIT WHAT"],
  ["SEE YOU NEXT LOOP, / FOOD COURT", "HOT SPY: ♥♥♥"],
]);
export const VISITS = {
  fashion: ["IT'S NOT A DISGUISE.", "IT'S A LOOK, SERGEI."],
  electronics: ["YOU'LL NEED BATTERIES.", "BEEP. NOT INCLUDED."],
  toys: ["DIMITRI, HE'S HERE!", "DA! HIDE THE TEDDIES!"],
  food: ["WANT FRIES WITH THAT?"],
  sports: ["THESE ARE MY GETAWAY SHOES", "BOTH LEFT FEET, COMRADE"],
  music: ["TURN IT UP, BORIS!"],
  lounge: ["TRY THE MASSAGE CHAIR..."],
  gadgets: ["BEEP. PLEASE DON'T TOUCH."],
  novelty: ["WHOA... THE LAVA LAMP..."],
};
export const LAST_WORDS = [
  "I WAS JUST BROWSING!",
  "WHAT'S YOUR RETURN POLICY?!",
  "I HAD A COUPON!",
  "TELL MY CAT...",
  "NOT THE FACE!",
  "I WAS ON MY LUNCH BREAK!",
  "WORTH IT. 70% OFF.",
  "MY RECEIPT...",
];
export const ELEVATOR_LINES = [
  "...NICE WEATHER.",
  "GOING DOWN? ME TOO.",
  "*AWKWARD COUGH*",
  "THIS IS MY FLOOR, ACTUALLY",
];
export const PA = [
  "ATTENTION SHOPPERS: CLEANUP ON 3F. AGAIN.",
  "FREE SAMPLES AT HOT SPY. NOT POISONED. PROBABLY.",
  "WILL THE OWNER OF A BLACK VAN MARKED 'NOT SPIES' PLEASE MOVE IT.",
  "LOST CHILD AT THE 2F KIOSK. SAYS HIS NAME IS AGENT 7.",
  "BLOCKBLUSTER IS STILL CLOSED. BE KIND, REWIND.",
  "THE MALL CLOSES AT 9. SPIES CLOSE AT NEVER.",
  "A REMINDER: SECURITY IS WATCHING. MOSTLY TV.",
].map((x) => wrap(x, 36));
export const HEADLINES = [
  "LOCAL AGENT FINDS 6 PACKAGES, STILL NO PARKING",
  "SPIES FOILED; FOOD COURT SALES UP 300%",
  "MAN ZIPLINES ONTO ROOF. SECURITY 'NOT SURPRISED'",
  "MALL WALKERS DEMAND APOLOGY FOR 'HEY!' INCIDENT",
  "GAMESTONK SHARE PRICE DOWN ANOTHER 99%",
].map((x) => wrap(x, 26));
export const ITEMS = [
  "EXPIRED COUPON",
  "PRE-OWNED STRATEGY GUIDE",
  "PET ROCK",
  "MOOD RING",
  "1 SHARE (DOWN 99%)",
];
export const FLOORS = ["R", "4F", "3F", "2F", "1F", "P"];
export const ANNOUNCE = [
  "ROOF - SKY HIGH PRICES",
  "4F - FASHION & GADGETS, SPIES",
  "3F - TOYS & QUESTIONABLE GIFTS",
  "2F - MUSIC & FOOD COURT",
  "1F - SHOES & MORE SHOES",
  "P - THANK YOU FOR SHOPLIFTING",
];
export const TEXT = {
  subtitle: "A SHOPPING MALL ESPIONAGE",
  studio: "FLICKERSOFT",
  presents: "PRESENTS",
  copyright: "(C) 2026 FLICKERSOFT",
  start: "PRESS START",
  directory: "MALL DIRECTORY",
  pause: "PAUSE",
  blackFriday: "BLACK FRIDAY!",
  discount: "70% OFF EVERYTHING",
  search: "PRESS X TO SEARCH",
  searching: "SEARCHING...",
  trap: "IT'S A TRAP!",
  nothing: "NOTHING HERE",
  occupied: "OCCUPIED!!",
  hey: "HEY!",
  cop: "HEY! STOP RIGHT THERE!",
  detained: "DETAINED! -500",
  sideB: "NOW PLAYING: SIDE B",
  cave: "IT'S DANGEROUS TO GO ALONE! TAKE THIS.",
  alarm: "ALARM! SECURITY ALERTED",
  closed: ["ATTENTION SHOPPERS:", "THE MALL IS NOW CLOSED"],
  exit: "6 PACKAGES. ONE GETAWAY.",
  roof: "UP / DOWN: CALL & RIDE",
  controls: "ARROWS MOVE  Z SHOOT  X JUMP",
  controls2: "ENTER START  SHIFT MAP  C CRT",
  photo: "PHOTO STRIP ADDED",
  paper: "THE DAILY MALL",
  edition: "LATE EDITION - 25 CENTS",
  clear: "MISSION COMPLETE",
  continue: "CONTINUE?",
  gameover: "GAME OVER",
  hudPkg: "PKG",
  hudLives: "L",
  bonus: "CLEAR BONUS",
  time: "TIME BONUS",
  package: "PACKAGE",
  loop: "LOOP",
  soundOn: "SOUND ON",
  soundOff: "SOUND OFF",
  crtOn: "CRT ON",
  crtOff: "CRT OFF",
  missing: "PACKAGES LEFT:",
  hold: "HOLD UP/DOWN TO DRIVE",
  out: "LEFT/RIGHT TO EXIT",
  hidden: "SHHH... PHOTO BOOTH",
  guide: "FIND 6 PACKAGES. ESCAPE ON P.",
  searchHint: "TOUCH A FIXTURE. TAP X.",
  next: "ENTER: NEXT",
  pausedHint: "ENTER TO RESUME",
  mapHint: "SHIFT: CLOSE DIRECTORY",
  kiosk: "NEAREST PACKAGE:",
  take: "YOU GOT:",
  photoStrip: "PHOTO STRIP",
  high: "HI",
  arriving: "SPECIAL DELIVERY",
  footer: "NO RECEIPT. NO PROBLEM.",
  radar: "RADAR",
  armor: "ARMOR",
  likes: "LIKES",
  locked: "CLOSED FOR QUESTIONING",
  ding: "DING!",
  score: "SCORE",
  packages: "PACKAGES",
  continues: "CONTINUES LEFT:",
  pickUp: "WALK TO THE PEDESTAL",
  splashHint: "ANY BUTTON TO SKIP",
};

// Small UI labels are centralized too; all prose can be edited in this module.
export const UI = {
  agentDown: "AGENT DOWN",
  lastReceipt: "LAST RECEIPT",
  backSoon: "BACK ON DUTY IN A MOMENT...",
  noRefunds: "NO REFUNDS.",
  mall: "MALL",
  action: "ACTION",
  galleria: "STARLIGHT GALLERIA",
  discount: "70%",
  closingSale: "CLOSING SALE",
  forLease: "FOR LEASE",
  getaway: "GETAWAY",
  play: "PLAY",
  yum: "YUM!",
  sale: "SALE",
  exit: "EXIT",
  sideB: "SIDE B",
  storeControls: "Z: SHOOT  X: SEARCH  DOWN: EXIT",
  legend1: "RED: PACKAGE  BLUE: POWER-UP",
  legend2: "GRAY: CLEAR   OUTLINE: CLOSED",
  noSouvenirs: "NO SOUVENIRS YET",
  spygram: "SPYGRAM",
  handle: "@AGENT_07",
  accomplished: "MISSION ACCOMPLISHED",
  rooftop: "ROOFTOP VIBES",
  resume: "ENTER: BACK TO BUSINESS",
  kept: "SCORE AND PACKAGES KEPT",
  atlas: "FLICKERSOFT SPRITE ATLAS",
  armorSaved: "ARMOR SAVED YOU",
  back: "BACK IN BUSINESS",
  allPackages: "ALL PACKAGES FOUND",
};
