import {STORES,TARGETS,SHAFTS,ESCALATORS,ROOM_PLANS,FLOOR_Y,FLOOR_BANNERS,POWERUPS,JOKE_ITEMS,FIRST_LINES,LAST_WORDS,PA_LINES,HEADLINES,POSTS_ARRIVE,POSTS_CLEAR,LEVEL_W} from './data.js';

export function nextRandom(s){let x=s.rng|0;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x|0;return (x>>>0)/4294967296}
const pick=(s,a)=>a[Math.floor(nextRandom(s)*a.length)];
const near=(a,b,n)=>Math.abs(a-b)<=n;
const evt=(s,type,extra={})=>s.events.push({type,...extra});
const banner=(s,text,t=120)=>{s.banner=text;s.bannerTimer=t};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const difficulty=loop=>({speed:Math.min(1.7,1+(loop-1)*.1),spawn:Math.max(60,300*Math.pow(.85,loop-1)),shot:Math.max(60,150*Math.pow(.85,loop-1)),alarm:Math.max(60,150-(loop-1)*20)*60});
export function score(s,n){const before=s.score;s.score=Math.max(0,s.score+n);if(before<20000&&s.score>=20000&&!s.extraLife){s.extraLife=true;s.lives++;banner(s,'EXTRA LIFE!',100);evt(s,'power')}}
function generateRoom(s,store){const plan=ROOM_PLANS[store.id]||[];const packageAt=store.role==='target'?Math.floor(nextRandom(s)*plan.length):-1;return {w:16,h:11,fixtures:plan.map(([x,y,kind],i)=>({x,y,kind,opened:false,content:i===packageAt?'package':store.role==='shop'?(nextRandom(s)<.72?'power':'empty'):(s.blackFriday?'power':nextRandom(s)<.16?'trap':nextRandom(s)<.3?'power':'empty')}))}}
export function createGame(seed=1,debug=false){const s={rng:(Number(seed)||1)|0,screen:debug?'title':'splash',frame:0,phase:0,loop:1,score:0,high:0,lives:3,continues:3,packages:0,blackFriday:false,konami:0,extraLife:false,elapsed:0,alarm:false,player:{x:50,y:40,floor:0,dir:1,vy:0,jump:0,duck:false,invuln:0,ride:null,roof:null,freeze:0,hidden:0,slide:0,callWait:0,safeX:50,safeFloor:0},elevators:SHAFTS.map((sh,i)=>({id:sh.id,x:sh.x,y:FLOOR_Y[i===1?1:0],floor:i===1?1:0,dir:0,goal:null,wait:120,occupied:false,called:false,auto:!sh.manual,dingFloor:null})),spies:[],bullets:[],lamps:[],coins:[],drops:[],guards:[],store:null,rooms:{},visited:{},power:{weapon:null,weaponTimer:0,speed:null,speedTimer:0,armor:false,radar:false,invincible:0},search:null,storeX:8,storeY:9,storeDir:'up',storeGrace:0,shotCd:0,spawnTimer:300,paTimer:3600,paLast:-1,wet:{x:365,timer:0},janitorX:310,walkers:[{x:100,dir:1},{x:550,dir:-1}],cop:{x:600,floor:3,dir:-1,angry:0},kioskCooldown:0,fountainCooldown:{},photo:false,photoStrip:false,gameEgg:false,eggItem:null,eggOwned:false,eggAwait:false,listening:false,toys:[],banner:'',bannerTimer:0,popup:[],clearStage:0,clearTimer:0,exitFired:false,continueTimer:540,gameOverTimer:0,selfie:pickSeedPost(seed,POSTS_ARRIVE),clearPost:null,headline:null,events:[]};setupLevel(s,true);s.screen=debug?'title':'splash';return s}
function pickSeedPost(seed,list){return list[Math.abs((Number(seed)||1)*2654435761|0)%list.length]}
function setupLevel(s,first=false){s.elapsed=0;s.alarm=false;s.packages=0;s.exitFired=false;s.rooms={};s.visited={};s.store=null;s.spies=[];s.bullets=[];s.guards=[];s.drops=[];s.lamps=[];s.coins=[];s.toys=[];s.fountainCooldown={};s.power={weapon:null,weaponTimer:0,speed:null,speedTimer:0,armor:false,radar:false,invincible:0};s.player={x:50,y:40,floor:0,dir:1,vy:0,jump:0,duck:false,invuln:120,ride:null,roof:null,freeze:0,hidden:0,slide:0,callWait:0,safeX:50,safeFloor:0};s.spawnTimer=300;s.elevators=SHAFTS.map((sh,i)=>({id:sh.id,x:sh.x,y:FLOOR_Y[i===1?1:0],floor:i===1?1:0,dir:0,goal:null,wait:120,occupied:false,called:false,auto:!sh.manual,dingFloor:null}));s.screen=first?'splash':'arrival';s.phase=0;s.selfie=pick(s,POSTS_ARRIVE);for(const [x,floor,ball] of [[160,1,false],[675,1,false],[405,2,false],[390,3,true],[570,3,true],[350,4,false]])s.lamps.push({x,floor,fall:0,broken:0,ball,dir:1})}
function currentButtons(input){return {h:input?.held||{},p:input?.pressed||{}}}
export function step(state,input={}){const s=structuredClone(state);s.events=[];const {h,p}=currentButtons(input);s.frame++;if(s.bannerTimer>0)s.bannerTimer--;if(s.phase>0)s.phase++;
 if(s.screen==='splash'){s.phase++;if(Object.values(p).some(Boolean)||s.phase>=180){s.screen='title';s.phase=0;evt(s,'title')}return s}
 if(s.screen==='title'){for(const b of ['up','down','left','right','b','a'])if(p[b]){const code=['up','up','down','down','left','right','left','right','b','a'];const want=code[s.konami];s.konami=b==='up'&&s.konami<=2?Math.min(2,s.konami+1):b===want?s.konami+1:b==='up'?1:0;if(s.konami===10){s.blackFriday=true;s.konami=0;banner(s,'BLACK FRIDAY! 70% OFF',240);evt(s,'power')}}if(p.start){setupLevel(s,true);s.screen='arrival';s.phase=0;evt(s,'zip')}return s}
 if(s.screen==='arrival'){s.phase++;const t=s.phase;if(t<80){s.player.x=clamp(50+t*1.65,50,182);s.player.y=8+t*.25}else if(t<105){s.player.x=182;s.player.y=28+(t-80)*.48}else{s.player.x=182;s.player.y=40}if(t===105){evt(s,'land');s.selfie=pick(s,POSTS_ARRIVE)}if(t===130)evt(s,'flash');if((t>130&&Object.values(p).some(Boolean))||t>=280){s.screen='mall';s.phase=0;s.player.x=182;s.player.floor=0;s.player.y=40;s.player.safeX=182}return s}
 if(s.screen==='map'||s.screen==='pause'){if(p.select&&s.screen==='map'||p.start&&s.screen==='pause'){s.screen=s.store?'store':'mall';evt(s,'pause')}return s}
 if(s.screen==='continue'){if(p.start){s.lives=3;s.continues--;s.screen=s.store?'store':'mall';s.player.invuln=120;s.player.freeze=0;s.power={weapon:null,weaponTimer:0,speed:null,speedTimer:0,armor:false,radar:s.power.radar,invincible:0};s.spies=[];s.bullets=[];s.guards=[];if(s.store)spawnGuards(s);evt(s,'power');return s}if(--s.continueTimer<=0){s.screen='gameover';s.phase=0;evt(s,'gameover')}else if(s.continueTimer%60===0)evt(s,'beep');return s}
 if(s.screen==='gameover'){s.phase++;if(s.phase>420||p.start&&s.phase>100){s.high=Math.max(s.high,s.score);s.screen='title';s.phase=0;s.score=0;s.lives=3;s.continues=3;s.loop=1;s.extraLife=false;s.blackFriday=false}s.gameOverTimer++;return s}
 if(s.screen==='clear'){s.clearTimer++;if(p.start){s.clearStage++;s.clearTimer=0}if(s.clearTimer>180){s.clearStage++;s.clearTimer=0}if(s.clearStage>=3){s.loop++;setupLevel(s,false)}return s}
 if(p.select){s.screen='map';evt(s,'pause');return s}if(p.start){s.screen='pause';evt(s,'pause');return s}
 s.elapsed++;if(!s.alarm&&s.elapsed>=difficulty(s.loop).alarm){s.alarm=true;banner(s,'ALARM! SECURITY ALERTED',160);evt(s,'alarm')}
 if(s.paTimer-->0){}else{let i=Math.floor(nextRandom(s)*PA_LINES.length);if(i===s.paLast)i=(i+1)%PA_LINES.length;s.paLast=i;s.paTimer=3600;banner(s,PA_LINES[i],210);evt(s,'pa')}
 tickPower(s);if(s.player.invuln>0)s.player.invuln--;if(s.player.freeze>0)s.player.freeze--;if(s.shotCd>0)s.shotCd--;if(s.kioskCooldown>0)s.kioskCooldown--;
 if(s.screen==='mall')updateMall(s,h,p);else updateStore(s,h,p);
 return s}
function tickPower(s){const q=s.power;for(const k of ['weaponTimer','speedTimer','invincible'])if(q[k]>0)q[k]--;if(!q.weaponTimer)q.weapon=null;if(!q.speedTimer)q.speed=null}
function die(s){if(s.player.invuln||s.power.invincible||s.screen==='arrival')return;if(s.power.armor){s.power.armor=false;s.player.invuln=60;banner(s,'ARMOR SAVED YOU!',75);evt(s,'hurt');return}s.lives--;evt(s,'death');s.spies=[];s.bullets=[];s.guards=[];s.player.freeze=0;s.player.hidden=0;s.power={weapon:null,weaponTimer:0,speed:null,speedTimer:0,armor:false,radar:s.power.radar,invincible:0};if(s.lives<=0){if(s.continues>0){s.screen='continue';s.continueTimer=540;evt(s,'continue')}else{s.screen='gameover';s.phase=0;evt(s,'gameover')}}else{if(s.store){s.store=null;s.screen='mall'}s.player.x=s.player.safeX;s.player.floor=s.player.safeFloor;s.player.y=FLOOR_Y[s.player.floor];s.player.jump=0;s.player.vy=0;s.player.ride=null;s.player.roof=null;s.player.invuln=120;banner(s,'TRY AGAIN, AGENT!',90)}}
function updateMall(s,h,p){const pl=s.player,boost=s.power.speed?1.5:1;const speed=boost;let horiz=(h.right?1:0)-(h.left?1:0);pl.duck=!!h.down&&!pl.ride;if(pl.hidden){pl.hidden--;if(!pl.hidden&&!s.photoStrip){s.photoStrip=true;banner(s,'PHOTO STRIP ACQUIRED!',120)}if(p.b||p.up){pl.hidden=0;if(!s.photoStrip){s.photoStrip=true;banner(s,'PHOTO STRIP ACQUIRED!',120)}}return}
 if(pl.freeze===0){if(pl.ride){driveElevator(s,h,p)}else{if(horiz){pl.dir=horiz;if(pl.slide)horiz=pl.dir;pl.x=clamp(pl.x+horiz*speed,8,LEVEL_W-8)}if(p.b&&pl.jump===0){pl.vy=-3.5*boost;pl.jump=-.01;evt(s,'jump')}if(pl.jump!==0){pl.jump+=pl.vy;pl.vy+=.31;if(pl.jump>=0){pl.jump=0;pl.vy=0}}if(h.up||h.down){if(p.up||p.down)interactMall(s,h)}if(s.screen!=='mall')return;if(p.a||h.a&&s.shotCd===0)shoot(s,'mall')}}
 if(pl.slide){pl.slide--;pl.x=clamp(pl.x+pl.dir*speed,8,LEVEL_W-8)}
 tickElevators(s);tickSpies(s);tickBullets(s);tickLamps(s);tickNPCs(s);tickDrops(s);
 if(pl.floor===4&&s.wet.timer>0&&near(pl.x,s.wet.x,24)&&pl.jump===0)pl.slide=48;
 if(!pl.ride&&pl.jump===0){const sh=SHAFTS.find(v=>near(pl.x,v.x,8)&&pl.floor>=v.min&&pl.floor<=v.max);if(sh){const e=s.elevators.find(v=>v.id===sh.id);if(e.y>FLOOR_Y[pl.floor]+4){const gap=Math.round((e.y-FLOOR_Y[pl.floor])/48);if(gap>1){die(s)}else{pl.floor=Math.min(pl.floor+1,5);pl.y=FLOOR_Y[pl.floor];pl.roof=e.id;evt(s,'land')}}else if(e.y<FLOOR_Y[pl.floor]-4&&e.dir>0&&!e.called){die(s)}}}
 pl.y=FLOOR_Y[pl.floor]+pl.jump;const callShaft=SHAFTS.find(v=>pl.floor>=v.min&&pl.floor<=v.max&&near(pl.x,v.x,19));if(callShaft&&!pl.ride&&!pl.jump&&!horiz){const car=s.elevators.find(v=>v.id===callShaft.id);if(!near(car.y,FLOOR_Y[pl.floor],2)&&++pl.callWait>=30&&car.goal!==pl.floor){car.goal=pl.floor;car.called=true;pl.callWait=0;evt(s,'call')}}else pl.callWait=0;if(pl.floor>0&&!pl.ride&&pl.jump===0&&pl.freeze===0){pl.safeX=pl.x;pl.safeFloor=pl.floor}
}
function interactMall(s,h){const pl=s.player,dir=h.up?'up':'down';if(pl.floor===5&&near(pl.x,725,27)){if(s.packages===6){clearLevel(s)}else{banner(s,`PACKAGES LEFT: ${6-s.packages}`);evt(s,'buzzer')}return}
 const st=STORES.find(v=>v.floor===pl.floor&&v.role!=='closed'&&near(v.x,pl.x,12)&&!(v.role==='target'&&s.rooms[v.id]?.cleared));if(st){enterStore(s,st);return}
 const sh=SHAFTS.find(v=>pl.floor>=v.min&&pl.floor<=v.max&&near(pl.x,v.x,19));if(sh){const e=s.elevators.find(v=>v.id===sh.id);if(near(e.y,FLOOR_Y[pl.floor],2)){pl.ride=e.id;pl.x=e.x;pl.jump=0;pl.y=e.y;e.occupied=true;banner(s,`SHAFT ${e.id}: ${FLOOR_BANNERS[pl.floor]}`,90);evt(s,'door')}else{e.goal=pl.floor;e.called=true;banner(s,`CALLING ELEVATOR ${e.id}`,60);evt(s,'call')}return}
 const esc=ESCALATORS.find(v=>near(pl.x,v.x,18)&&(pl.floor===v.a||pl.floor===v.b));if(esc){if(dir==='up'&&pl.floor===esc.b||dir==='down'&&pl.floor===esc.a){pl.floor=pl.floor===esc.a?esc.b:esc.a;pl.y=FLOOR_Y[pl.floor];pl.x=esc.x+(dir==='up'?-17:17);evt(s,'escalator');return}}
 if(pl.floor===2&&near(pl.x,610,19)){pl.hidden=300;evt(s,'door');banner(s,'SAY CHEESE!',60);return}
 if(pl.floor>0&&pl.floor<5&&near(pl.x,30+pl.floor*20,16)&&s.kioskCooldown===0){const remaining=TARGETS.find(v=>!s.rooms[v.id]?.cleared);banner(s,remaining?`DIRECTORY: ${remaining.name} ${remaining.floor}F`:'ALL PACKAGES FOUND!',150);s.kioskCooldown=1200;evt(s,'beep')}
}
function driveElevator(s,h,p){const pl=s.player,e=s.elevators.find(v=>v.id===pl.ride),sh=SHAFTS.find(v=>v.id===e.id);if(!e.dir&&(p.left||p.right||h.left||h.right)){pl.ride=null;e.occupied=false;pl.x=e.x+(h.left||p.left?-16:16);pl.floor=e.floor;pl.y=FLOOR_Y[pl.floor];evt(s,'door');return}if(e.auto)return;if(h.up&&e.y>FLOOR_Y[sh.min])e.dir=-1;if(h.down&&e.y<FLOOR_Y[sh.max])e.dir=1;if(!h.up&&!h.down&&e.dir&&e.goal===null){e.goal=clamp(Math.round((e.y-FLOOR_Y[0])/48)+(e.dir>0?1:0),sh.min,sh.max)}pl.x=e.x;pl.y=e.y}
function tickElevators(s){for(const e of s.elevators){const sh=SHAFTS.find(v=>v.id===e.id);if(e.auto&&!e.occupied){if(e.wait>0)e.wait--;else if(!e.dir){let f=sh.min+Math.floor(nextRandom(s)*(sh.max-sh.min+1));if(f===e.floor)f=f===sh.max?sh.min:f+1;e.goal=f;e.dir=Math.sign(FLOOR_Y[f]-e.y);e.wait=120}}if(e.goal!==null&&!e.dir){e.dir=Math.sign(FLOOR_Y[e.goal]-e.y)}if(e.dir){e.y+=e.dir;if(e.goal!==null){if(e.y===FLOOR_Y[e.goal])stopElevator(s,e)}else{const f=FLOOR_Y.findIndex((y,i)=>i>=sh.min&&i<=sh.max&&y===e.y);if(f>=0){if(e.occupied&&s.player.ride===e.id&&((e.dir<0&&e.y===FLOOR_Y[sh.min])||(e.dir>0&&e.y===FLOOR_Y[sh.max])))stopElevator(s,e);else if(!e.occupied)stopElevator(s,e)}}}if(e.occupied&&s.player.ride===e.id){s.player.y=e.y;s.player.floor=clamp(Math.round((e.y-40)/48),sh.min,sh.max)}for(const spy of s.spies)if(spy.floor>=sh.min&&spy.floor<=sh.max&&near(spy.x,e.x,9)&&e.dir>0&&near(e.y,FLOOR_Y[spy.floor],3)){killSpy(s,spy,300);if(!e.called&&s.player.roof===e.id&&e.y<=FLOOR_Y[sh.min])die(s)}}}
function stopElevator(s,e){const f=FLOOR_Y.indexOf(e.y);if(f<0)return;e.floor=f;e.dir=0;e.goal=null;e.called=false;if(e.dingFloor!==f){evt(s,'ding');e.dingFloor=f}if(e.occupied&&s.player.ride===e.id){s.player.floor=f;banner(s,FLOOR_BANNERS[f],100)}e.wait=120}
function spawnSpy(s){const pl=s.player,cap=s.blackFriday?8:4;if(s.spies.filter(v=>v.hp>0).length>=cap)return;const doors=STORES.filter(v=>v.role!=='closed'&&Math.abs(v.floor-pl.floor)<=1&&Math.abs(v.x-pl.x)>=64&&Math.abs(v.x-pl.x)<=200&&!(v.role==='target'&&s.rooms[v.id]?.cleared));if(!doors.length)return;const st=pick(s,doors);s.spies.push({x:st.x,y:FLOOR_Y[st.floor],floor:st.floor,dir:st.x>pl.x?-1:1,age:0,shot:0,aim:0,low:false,hp:1,dead:0,dodge:false,wait:0});evt(s,'door')}
function tickSpies(s){if(--s.spawnTimer<=0){spawnSpy(s);s.spawnTimer=Math.round(difficulty(s.loop).spawn/(s.blackFriday?2:1)/(s.alarm?1.3:1))}const pl=s.player;for(const spy of s.spies){if(spy.dead){spy.dead--;continue}spy.age++;if(spy.aim){spy.aim--;if(!spy.aim){s.bullets.push({x:spy.x+spy.dir*8,y:FLOOR_Y[spy.floor]-(spy.low?6:13),vx:spy.dir*2,vy:0,owner:'spy',floor:spy.floor});evt(s,'enemyShot');spy.shot=Math.round(difficulty(s.loop).shot)}continue}if(spy.shot>0)spy.shot--;if(spy.wait>0){spy.wait--;continue}const sees=pl.floor===spy.floor&&Math.abs(pl.x-spy.x)<160&&!pl.hidden&&pl.invuln<110;if(sees){spy.dir=pl.x>spy.x?1:-1;if(Math.abs(pl.x-spy.x)>40)spy.x+=spy.dir*.55*difficulty(s.loop).speed*(s.alarm?1.25:1);if(spy.age>=120&&spy.shot<=0){spy.aim=30;spy.low=nextRandom(s)<.5;spy.dodge=nextRandom(s)<.1;evt(s,'aim')}}else if(spy.age%90===0){spy.dir=nextRandom(s)<.5?-1:1;spy.wait=20}else spy.x+=spy.dir*.23;spy.x=clamp(spy.x,12,756);if(spy.floor===pl.floor&&near(spy.x,pl.x,11)&&pl.jump===0){if(s.power.invincible)killSpy(s,spy,100);else die(s)}if(spy.floor===pl.floor&&near(spy.x,pl.x,13)&&pl.jump< -5&&Math.sign(spy.x-pl.x)===pl.dir){killSpy(s,spy,100)}}s.spies=s.spies.filter(v=>!v.dead||v.dead>0)}
function killSpy(s,spy,points=100){if(spy.dead)return;spy.dead=24;spy.hp=0;score(s,points);evt(s,points>100?'crush':'hit');if(nextRandom(s)<.35)banner(s,pick(s,LAST_WORDS),70);if(nextRandom(s)<.05)s.drops.push({x:spy.x,floor:spy.floor,kind:nextRandom(s)<.5?'CINNABOMB':pick(s,POWERUPS),life:600})}
function shoot(s,where){const cap=s.power.weapon==='RAPID FIRE'?4:2;if(s.bullets.filter(b=>b.owner==='player').length>=cap)return;s.shotCd=s.power.weapon==='RAPID FIRE'?8:18;const pl=s.player,dir=where==='mall'?pl.dir:s.storeDir;const vectors=where==='mall'?[[pl.dir*4,0]]:dir==='up'?[[0,-4]]:dir==='down'?[[0,4]]:dir==='left'?[[-4,0]]:[[4,0]];if(s.power.weapon==='SPREAD SHOT')vectors.push([vectors[0][0]||-1,-1],[vectors[0][0]||1,1]);for(const [vx,vy] of vectors)s.bullets.push({x:where==='mall'?pl.x:pl.x,y:where==='mall'?FLOOR_Y[pl.floor]-(pl.duck?6:13):pl.y,vx,vy,owner:'player',floor:pl.floor,store:where==='store'});evt(s,'shot');if(where==='mall'&&s.cop.floor===pl.floor&&near(s.cop.x,pl.x,128)&&s.cop.dir===-pl.dir){s.cop.angry=600;banner(s,'HEY! STOP RIGHT THERE!',120);evt(s,'whistle')}}
function tickBullets(s){const pl=s.player;for(const b of s.bullets){b.x+=b.vx;b.y+=b.vy;if(b.owner==='player'){for(const spy of s.spies)if(!spy.dead&&spy.floor===b.floor&&near(spy.x,b.x,7)&&near(FLOOR_Y[spy.floor]-13,b.y,11)){if(!(spy.dodge&&b.y<FLOOR_Y[spy.floor]-9)){killSpy(s,spy);b.life=0;break}}for(const lamp of s.lamps)if(lamp.floor===b.floor&&!lamp.fall&&!lamp.broken&&near(lamp.x,b.x,5)){lamp.fall=1;lamp.dir=Math.sign(b.vx)||1;b.life=0;evt(s,'lamp');break}for(const walker of s.walkers)if(b.floor===3&&near(walker.x,b.x,6)){score(s,-200);banner(s,'HEY!',70);b.life=0;evt(s,'ping')}for(const fountain of [115,565]){const key=`${b.floor}:${fountain}`;if((b.floor===2||b.floor===4)&&near(b.x,fountain,9)&&!s.fountainCooldown[key]){const gold=nextRandom(s)<.05;for(let i=0;i<4;i++)s.coins.push({x:fountain+(i-2)*8,floor:b.floor,timer:180,gold:gold&&i===2});s.fountainCooldown[key]=900;b.life=0;evt(s,'coins')}}}else if(pl.floor===b.floor&&near(pl.x,b.x,8)&&near(FLOOR_Y[pl.floor]-(pl.duck?5:12)+pl.jump,b.y,8)){if(!pl.duck||b.y>FLOOR_Y[pl.floor]-10)die(s);b.life=0}if(b.life===undefined)b.life=120;else b.life--}s.bullets=s.bullets.filter(b=>b.life>0&&b.x>0&&b.x<LEVEL_W&&b.y>0&&b.y<300)}
function tickLamps(s){for(const l of s.lamps){if(l.broken){l.broken--;continue}if(l.fall){l.fall++;if(l.fall>=15){if(l.floor===s.player.floor&&near(l.x,s.player.x,12))die(s);for(const spy of s.spies)if(spy.floor===l.floor&&near(l.x,spy.x,16))killSpy(s,spy,300);if(l.ball){l.x+=l.dir*2;if(l.x>10&&l.x<758&&l.fall<100)continue}l.fall=0;l.broken=120;evt(s,'glass')}}}}
function tickNPCs(s){s.janitorX+=Math.sin(s.elapsed/100)*.3;if(s.elapsed%600===0){s.wet={x:clamp(s.janitorX,250,390),timer:600}}if(s.wet.timer>0)s.wet.timer--;for(const key of Object.keys(s.fountainCooldown))if(--s.fountainCooldown[key]<=0)delete s.fountainCooldown[key];for(const w of s.walkers){w.x+=w.dir*.5;if(w.x<90||w.x>640)w.dir*=-1;if(s.player.floor===3&&near(w.x,s.player.x,8))s.player.x=clamp(s.player.x+w.dir,8,LEVEL_W-8)}const c=s.cop;c.x+=c.dir*(c.angry?1.2:.3);if(c.x<40||c.x>735)c.dir*=-1;if(c.angry){c.angry--;if(c.floor===s.player.floor&&near(c.x,s.player.x,10)){s.player.freeze=180;score(s,-500);banner(s,'DETAINED! -500',120);c.angry=0;evt(s,'whistle')}}}
function tickDrops(s){for(const d of s.drops){d.life--;if(d.floor===s.player.floor&&near(d.x,s.player.x,10)){grantPower(s,d.kind);d.life=0}}s.drops=s.drops.filter(d=>d.life>0);for(const c of s.coins){c.timer--;if(c.floor===s.player.floor&&near(c.x,s.player.x,10)){score(s,50);if(c.gold){s.lives++;banner(s,'GOLD COIN! 1-UP',90)}c.timer=0;evt(s,'coins')}}s.coins=s.coins.filter(c=>c.timer>0)}
export function grantPower(s,name){const q=s.power;score(s,50);switch(name){case 'RAPID FIRE':case 'SPREAD SHOT':q.weapon=name;q.weaponTimer=1200;break;case 'SNEAKERS':case 'ORANGE JULI-OOZE':q.speed=name;q.speedTimer=name==='SNEAKERS'?1200:720;break;case 'ARMOR VEST':case 'SOFT PRETZEL':q.armor=true;break;case 'RADAR':q.radar=true;break;case '1-UP':s.lives++;break;case 'CINNABOMB':q.invincible=360;break}banner(s,name,120);evt(s,'power')}
function enterStore(s,st){s.store=st.id;s.screen='store';s.storeX=8;s.storeY=9;s.storeDir='up';s.search=null;s.storeGrace=90;if(!s.rooms[st.id])s.rooms[st.id]=generateRoom(s,st);s.player.x=s.rooms[st.id].w*8;s.player.y=s.rooms[st.id].h*16-24;spawnGuards(s);if(!s.visited[st.id]){s.visited[st.id]=true;banner(s,FIRST_LINES[st.id]?.[0]||'WELCOME, AGENT!',120)}if(st.id==='game'&&!s.gameEgg){s.gameEgg=true;s.eggItem=pick(s,JOKE_ITEMS);s.eggTimer=180;s.eggAwait=false;banner(s,"IT'S DANGEROUS TO GO ALONE!",180)}evt(s,'door')}
function spawnGuards(s){const n=1+Math.floor(nextRandom(s)*3);s.guards=Array.from({length:n},(_,i)=>({x:50+i*72,y:66+i%2*40,dx:i%2?1:-1,hp:i===1?3:1,bot:i===1,shot:150,stun:0}))}
function leaveStore(s){const st=STORES.find(v=>v.id===s.store);s.store=null;s.screen='mall';s.listening=false;s.player.x=st.x;s.player.floor=st.floor;s.player.y=FLOOR_Y[st.floor];s.player.safeX=st.x;s.player.safeFloor=st.floor;s.player.invuln=60;s.guards=[];s.bullets=[];s.search=null;evt(s,'door')}
function updateStore(s,h,p){const st=STORES.find(v=>v.id===s.store),room=s.rooms[st.id],pl=s.player;if(s.eggTimer>0){s.eggTimer--;if(s.eggTimer===0){s.eggAwait=true;banner(s,'TAKE THIS.',120)}return}if(pl.freeze>0)return;
 if(s.search){if(p.a||p.up||p.down||p.left||p.right){s.search=null;banner(s,'SEARCH CANCELLED',45)}else if(--s.search.timer<=0){const f=room.fixtures[s.search.index];s.search=null;finishSearch(s,st,f)}return}
 let dx=(h.right?1:0)-(h.left?1:0),dy=(h.down?1:0)-(h.up?1:0);if(dy)dx=0;const speed=s.power.speed?1.5:1;if(dx||dy){s.storeDir=dy<0?'up':dy>0?'down':dx<0?'left':'right';const nx=clamp(pl.x+dx*speed,12,room.w*16-12),ny=clamp(pl.y+dy*speed,20,room.h*16-5);if(!room.fixtures.some(f=>near(nx,f.x*16+8,12)&&near(ny,f.y*16+8,12))){pl.x=nx;pl.y=ny}else{const ax=clamp(pl.x+dx*speed,12,room.w*16-12),ay=clamp(pl.y+dy*speed,20,room.h*16-5);if(dx&&!room.fixtures.some(f=>near(ax,f.x*16+8,12)&&near(pl.y+3,f.y*16+8,12)))pl.x=ax;else if(dy&&!room.fixtures.some(f=>near(pl.x+3,f.x*16+8,12)&&near(ay,f.y*16+8,12)))pl.y=ay}}if(s.eggAwait&&near(pl.x,128,12)&&near(pl.y,88,12)){s.eggAwait=false;s.eggOwned=true;score(s,1);banner(s,`YOU GOT: ${s.eggItem}`,180);evt(s,'item')}s.listening=st.id==='sam'&&room.fixtures.some(f=>f.kind==='booth'&&near(pl.x,f.x*16+8,8)&&near(pl.y,f.y*16+8,8));if(s.listening&&s.frame%60===0)banner(s,'NOW PLAYING: SIDE B',80);if(pl.y>=room.h*16-7&&near(pl.x,room.w*8,18)&&h.down){leaveStore(s);return}
 if(p.b){const fi=findTouchingFixture(s);if(fi>=0){s.search={index:fi,timer:s.power.speed?30:45};const f=room.fixtures[fi];s.storeDir=Math.abs(pl.x-(f.x*16+8))>Math.abs(pl.y-(f.y*16+8))?(pl.x<f.x*16+8?'right':'left'):(pl.y<f.y*16+8?'down':'up');evt(s,'search')}}if(p.a||h.a&&s.shotCd===0)shoot(s,'store');tickStoreGuards(s);tickStoreBullets(s);tickToys(s)}
export function findTouchingFixture(s){const room=s.rooms[s.store];return room.fixtures.findIndex(f=>!f.opened&&Math.abs(s.player.x-(f.x*16+8))<=19&&Math.abs(s.player.y-(f.y*16+8))<=19)}
function finishSearch(s,st,f){if(st.id==='forever'&&f.kind==='fitting'&&nextRandom(s)<.25){s.guards.push({x:f.x*16+8,y:f.y*16+8,dx:1,hp:1,bot:false,shot:90,stun:0});banner(s,'OCCUPIED!!',100);evt(s,'shriek');return}f.opened=true;if(f.content==='package'){s.packages++;s.rooms[st.id].cleared=true;score(s,500);banner(s,`PACKAGE ${s.packages}/6`,150);evt(s,'package')}else if(f.content==='power')grantPower(s,st.id==='hot'?pick(s,POWERUPS.slice(6)):pick(s,POWERUPS));else if(f.content==='trap'){plStun(s);banner(s,"IT'S A TRAP!",90);evt(s,'smoke')}else{banner(s,'NOTHING HERE',75);evt(s,'smoke')}}
function plStun(s){s.player.freeze=60}
function tickStoreGuards(s){if(s.storeGrace>0){s.storeGrace--;if(s.storeGrace===30&&FIRST_LINES[s.store]?.[1])banner(s,FIRST_LINES[s.store][1],80)}for(const g of s.guards){if(g.stun){g.stun--;continue}const pl=s.player;if(!g.bot&&s.storeGrace===0){g.dx=pl.x>g.x?1:-1}g.x+=g.dx*(g.bot?.45:.35);if(g.x<25||g.x>230)g.dx*=-1;if(near(g.x,pl.x,10)&&near(g.y,pl.y,10))die(s);if(--g.shot<=0&&s.storeGrace===0&&(near(g.x,pl.x,6)||near(g.y,pl.y,6))){s.bullets.push({x:g.x,y:g.y,vx:near(g.y,pl.y,6)?Math.sign(pl.x-g.x)*2:0,vy:near(g.x,pl.x,6)?Math.sign(pl.y-g.y)*2:0,owner:'guard',store:true,life:100});g.shot=Math.round(difficulty(s.loop).shot);evt(s,'enemyShot')}}}
function tickStoreBullets(s){for(const b of s.bullets){b.x+=b.vx;b.y+=b.vy;b.life=(b.life||100)-1;if(b.owner==='player'){for(const g of s.guards)if(near(g.x,b.x,8)&&near(g.y,b.y,8)){g.hp--;b.life=0;if(g.hp<=0){score(s,100);evt(s,'hit')}else evt(s,'ping')}}else if(near(s.player.x,b.x,7)&&near(s.player.y,b.y,7)){die(s);b.life=0}if(b.owner==='player'&&s.store==='kgb')for(const f of s.rooms.kgb.fixtures)if(f.kind==='shelf'&&near(f.x*16+8,b.x,9)&&near(f.y*16+8,b.y,9)){for(let i=0;i<3;i++)s.toys.push({x:b.x+i*5,y:b.y,dir:i%2?1:-1,timer:180});b.life=0;evt(s,'power')}}s.guards=s.guards.filter(g=>g.hp>0);s.bullets=s.bullets.filter(b=>b.life>0&&b.x>8&&b.x<248&&b.y>16&&b.y<176)}
function tickToys(s){for(const t of s.toys){t.x+=t.dir;t.timer--;if(t.x<16||t.x>240)t.dir*=-1;for(const g of s.guards)if(near(g.x,t.x,8)&&near(g.y,t.y,8))g.stun=90;if(s.store==='kgb')for(const f of s.rooms.kgb.fixtures)if(f.content==='trap'&&!f.opened&&near(t.x,f.x*16+8,8)&&near(t.y,f.y*16+8,8)){f.opened=true;for(const g of s.guards)if(near(g.x,t.x,24)&&near(g.y,t.y,24))g.stun=90;evt(s,'smoke')}}s.toys=s.toys.filter(t=>t.timer>0)}
function clearLevel(s){if(s.exitFired)return;s.exitFired=true;s.screen='clear';s.clearStage=0;s.clearTimer=0;const timeBonus=Math.max(0,300-Math.floor(s.elapsed/60))*10;score(s,1000+timeBonus);s.headline=pick(s,HEADLINES);s.clearPost=pick(s,POSTS_CLEAR);evt(s,'clear')}
export function roomFor(s,id){return s.rooms[id]}
